/**
 * Southeast US + federal construction portal catalog (pass-12).
 *
 * Comprehensive coverage for construction GCs and subs operating in the
 * southeast US. Adds:
 *
 *   - State procurement + DOT for AL / AR / FL / GA / KY / LA / MS / NC /
 *     SC / TN / VA / WV
 *   - Top counties per state (population / construction activity weighted)
 *   - Top cities per state
 *   - State authorities (turnpike, ports, water, transit, school boards)
 *   - Federal expansion: USACE SE districts, NAVFAC SE, Air Force bases,
 *     Army installations, NASA SE centers, VA SE regions, USDA, EPA
 *     Region 4, NPS SE, Coast Guard SE.
 *
 * Every entry has a verified-or-best-known canonical URL. scraperKind
 * defaults to MANUAL until a real scraper is implemented + tested. URLs
 * here have been triaged against the probe output: 404s and 403s have
 * been corrected to the right canonical URL; portals that genuinely
 * have no public page get MANUAL with that fact in the description.
 */

import type { PortalSeed } from "./portal-catalog";

export const SE_PORTAL_CATALOG: PortalSeed[] = [
  // ════════════════════════════════════════════════════════════════════
  // FEDERAL EXPANSION — USACE districts (the SE / Atlantic ones GCs work)
  // ════════════════════════════════════════════════════════════════════
  { name: "USACE Charleston District", url: "https://www.sac.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Charleston District", geoScope: "REGIONAL", geoState: "SC", description: "Charleston District — civil works + military construction across SC and parts of NC/GA.", naicsFocus: "236220, 237310" },
  { name: "USACE Wilmington District", url: "https://www.saw.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Wilmington District", geoScope: "REGIONAL", geoState: "NC", description: "Wilmington District — coastal NC, parts of VA and SC.", naicsFocus: "236220, 237310" },
  { name: "USACE Norfolk District", url: "https://www.nao.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Norfolk District", geoScope: "REGIONAL", geoState: "VA", description: "Norfolk District — Hampton Roads + VA waterways + DoD facilities.", naicsFocus: "236220, 237310" },
  { name: "USACE Savannah District", url: "https://www.sas.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Savannah District", geoScope: "REGIONAL", geoState: "GA", description: "Savannah District — coastal GA + SC; military + civil works.", naicsFocus: "236220, 237310" },
  { name: "USACE Mobile District", url: "https://www.sam.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Mobile District", geoScope: "REGIONAL", geoState: "AL", description: "Mobile District — AL, MS, FL panhandle, GA. Heavy military + civil works.", naicsFocus: "236220, 237310" },
  { name: "USACE Jacksonville District", url: "https://www.saj.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Jacksonville District", geoScope: "REGIONAL", geoState: "FL", description: "Jacksonville District — most of FL + Caribbean. Everglades restoration + flood control.", naicsFocus: "237310, 237990" },
  { name: "USACE Nashville District", url: "https://www.lrn.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Nashville District", geoScope: "REGIONAL", geoState: "TN", description: "Nashville District — TN, KY, parts of GA / AL / MS / VA.", naicsFocus: "237310, 237130" },
  { name: "USACE Memphis District", url: "https://www.mvm.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Memphis District", geoScope: "REGIONAL", geoState: "TN", description: "Memphis District — Mississippi River + AR / TN / MS / MO. Levee + flood-control heavy.", naicsFocus: "237310, 237990" },
  { name: "USACE Vicksburg District", url: "https://www.mvk.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Vicksburg District", geoScope: "REGIONAL", geoState: "MS", description: "Vicksburg District — MS, LA, AR. Major civil works on the Mississippi.", naicsFocus: "237310, 237990" },
  { name: "USACE New Orleans District", url: "https://www.mvn.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE New Orleans District", geoScope: "REGIONAL", geoState: "LA", description: "New Orleans District — Mississippi delta + LA coast. Hurricane protection systems.", naicsFocus: "237310, 237990" },
  { name: "USACE Louisville District", url: "https://www.lrl.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Louisville District", geoScope: "REGIONAL", geoState: "KY", description: "Louisville District — KY + parts of OH, IN, IL.", naicsFocus: "237310, 236220" },
  { name: "USACE Huntington District", url: "https://www.lrh.usace.army.mil/Business-With-Us/", category: "USACE district", agencyKind: "FEDERAL", agencyTier: "USACE", agencyName: "USACE Huntington District", geoScope: "REGIONAL", geoState: "WV", description: "Huntington District — WV, parts of KY, OH, VA.", naicsFocus: "237310" },

  // ════════════════════════════════════════════════════════════════════
  // FEDERAL EXPANSION — DoD installations (SE-relevant)
  // ════════════════════════════════════════════════════════════════════
  { name: "Eglin AFB Contracting (96 CONS)", url: "https://www.eglin.af.mil/Units/96-Mission-Support-Group/", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Eglin AFB", geoScope: "REGIONAL", geoState: "FL", description: "Eglin Air Force Base contracting — large Air Force facility maintenance + MILCON.", naicsFocus: "236220" },
  { name: "Hurlburt Field Contracting", url: "https://www.hurlburt.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Hurlburt Field", geoScope: "REGIONAL", geoState: "FL", description: "Air Force Special Operations Command HQ; sub MACCs through Eglin.", naicsFocus: "236220" },
  { name: "Tyndall AFB Contracting", url: "https://www.tyndall.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Tyndall AFB", geoScope: "REGIONAL", geoState: "FL", description: "Tyndall AFB — substantial post-Hurricane Michael MILCON program ongoing.", naicsFocus: "236220" },
  { name: "Robins AFB Contracting", url: "https://www.robins.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Robins AFB", geoScope: "REGIONAL", geoState: "GA", description: "Robins AFB — Warner Robins Air Logistics Complex.", naicsFocus: "236220" },
  { name: "Maxwell AFB Contracting", url: "https://www.maxwell.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Maxwell AFB", geoScope: "REGIONAL", geoState: "AL", description: "Maxwell AFB — Air University HQ + facility ops.", naicsFocus: "236220" },
  { name: "Joint Base Langley-Eustis", url: "https://www.jble.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "JBLE", geoScope: "REGIONAL", geoState: "VA", description: "Joint Base Langley-Eustis — combined Air Force + Army facility in Hampton Roads.", naicsFocus: "236220" },
  { name: "Shaw AFB Contracting", url: "https://www.shaw.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Shaw AFB", geoScope: "REGIONAL", geoState: "SC", description: "Shaw AFB — Air Combat Command 9th Air Force HQ.", naicsFocus: "236220" },
  { name: "Charleston Joint Base Contracting", url: "https://www.jbcharleston.jb.mil", category: "Joint base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "JB Charleston", geoScope: "REGIONAL", geoState: "SC", description: "Joint Base Charleston — Air Force + Navy combined operations.", naicsFocus: "236220" },
  { name: "Fort Liberty (Bragg) Contracting", url: "https://home.army.mil/liberty/contracting", category: "Army installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Fort Liberty", geoScope: "REGIONAL", geoState: "NC", description: "Fort Liberty (formerly Bragg) — largest US Army installation by population.", naicsFocus: "236220" },
  { name: "Fort Moore (Benning) Contracting", url: "https://home.army.mil/moore", category: "Army installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Fort Moore", geoScope: "REGIONAL", geoState: "GA", description: "Fort Moore (formerly Benning) — Maneuver Center of Excellence.", naicsFocus: "236220" },
  { name: "Fort Stewart Contracting", url: "https://home.army.mil/stewart", category: "Army installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Fort Stewart", geoScope: "REGIONAL", geoState: "GA", description: "Fort Stewart — 3rd Infantry Division.", naicsFocus: "236220" },
  { name: "Fort Jackson Contracting", url: "https://home.army.mil/jackson", category: "Army installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Fort Jackson", geoScope: "REGIONAL", geoState: "SC", description: "Fort Jackson — Army basic combat training installation.", naicsFocus: "236220" },
  { name: "Fort Campbell Contracting", url: "https://home.army.mil/campbell", category: "Army installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Fort Campbell", geoScope: "REGIONAL", geoState: "KY", description: "Fort Campbell — 101st Airborne Division HQ.", naicsFocus: "236220" },
  { name: "Fort Knox Contracting", url: "https://home.army.mil/knox", category: "Army installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Fort Knox", geoScope: "REGIONAL", geoState: "KY", description: "Fort Knox — Cadet Command + Human Resources Command.", naicsFocus: "236220" },
  { name: "MacDill AFB Contracting", url: "https://www.macdill.af.mil", category: "Air Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "MacDill AFB", geoScope: "REGIONAL", geoState: "FL", description: "MacDill AFB — CENTCOM + SOCOM HQ.", naicsFocus: "236220" },
  { name: "Patrick SFB / Cape Canaveral", url: "https://www.patrick.spaceforce.mil", category: "Space Force base", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Patrick Space Force Base", geoScope: "REGIONAL", geoState: "FL", description: "Eastern Range support — Cape Canaveral SFS + Patrick SFB.", naicsFocus: "236220" },
  { name: "NAS Pensacola Contracting", url: "https://cnrse.cnic.navy.mil/Installations/NAS-Pensacola/", category: "Navy installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "NAS Pensacola", geoScope: "REGIONAL", geoState: "FL", description: "Naval Air Station Pensacola — Naval Aviation Schools Command.", naicsFocus: "236220" },
  { name: "NAS Jacksonville Contracting", url: "https://cnrse.cnic.navy.mil/Installations/NAS-Jacksonville/", category: "Navy installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "NAS Jacksonville", geoScope: "REGIONAL", geoState: "FL", description: "Naval Air Station Jacksonville — patrol + maintenance ops.", naicsFocus: "236220" },
  { name: "Naval Station Norfolk Contracting", url: "https://cnrma.cnic.navy.mil/Installations/NAVSTA-Norfolk/", category: "Navy installation", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "Naval Station Norfolk", geoScope: "REGIONAL", geoState: "VA", description: "World's largest naval base. Continuous facility upgrade program.", naicsFocus: "236220" },
  { name: "NAVFAC Southeast Construction", url: "https://www.navfac.navy.mil/navfac_worldwide/atlantic/fecs/southeast.html", category: "DoD construction", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "NAVFAC Southeast", geoScope: "REGIONAL", description: "NAVFAC Southeast — naval facilities across SE US (FL, GA, SC, MS, AL).", naicsFocus: "236220", setAsideFocus: "SDVOSB, 8(a), HUBZONE" },
  { name: "NAVFAC Mid-Atlantic Construction", url: "https://www.navfac.navy.mil/navfac_worldwide/atlantic/fecs/midatlantic.html", category: "DoD construction", agencyKind: "FEDERAL", agencyTier: "DOD", agencyName: "NAVFAC Mid-Atlantic", geoScope: "REGIONAL", description: "NAVFAC Mid-Atlantic — VA + Hampton Roads concentration.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // FEDERAL EXPANSION — NASA SE centers, VA medical
  // ════════════════════════════════════════════════════════════════════
  { name: "NASA Marshall Space Flight Center", url: "https://www.nasa.gov/marshall/about/business-with-marshall/", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "NASA Marshall", geoScope: "REGIONAL", geoState: "AL", description: "NASA Marshall Space Flight Center — major facility construction at Redstone Arsenal.", naicsFocus: "236220, 541330" },
  { name: "NASA Kennedy Space Center", url: "https://www.nasa.gov/kennedy/business-with-kennedy/", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "NASA KSC", geoScope: "REGIONAL", geoState: "FL", description: "Kennedy Space Center — multi-billion-dollar Artemis program facility build-out.", naicsFocus: "236220, 237990" },
  { name: "NASA Stennis Space Center", url: "https://www.nasa.gov/stennis/working-with-nasa/", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "NASA Stennis", geoScope: "REGIONAL", geoState: "MS", description: "Stennis — rocket engine test facility. Regular construction + maintenance.", naicsFocus: "236220" },
  { name: "NASA Langley Research Center", url: "https://www.nasa.gov/langley/business-with-langley/", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "NASA Langley", geoScope: "REGIONAL", geoState: "VA", description: "Langley Research Center — aeronautics + space science facility ops.", naicsFocus: "236220" },
  { name: "VA Mid-Atlantic Health Care Network (VISN 6)", url: "https://www.va.gov/mid-atlantic-health-care/", category: "VA medical", agencyKind: "FEDERAL", agencyTier: "VA", agencyName: "VA VISN 6", geoScope: "REGIONAL", description: "VA Mid-Atlantic — covers VA / NC / WV medical center construction.", naicsFocus: "236220, 238210", setAsideFocus: "SDVOSB" },
  { name: "VA Sunshine Healthcare Network (VISN 8)", url: "https://www.visn8.va.gov", category: "VA medical", agencyKind: "FEDERAL", agencyTier: "VA", agencyName: "VA VISN 8", geoScope: "REGIONAL", description: "VA Sunshine Network — FL + Caribbean medical facility construction.", naicsFocus: "236220", setAsideFocus: "SDVOSB" },
  { name: "VA Southeast Network (VISN 7)", url: "https://www.visn7.va.gov", category: "VA medical", agencyKind: "FEDERAL", agencyTier: "VA", agencyName: "VA VISN 7", geoScope: "REGIONAL", description: "VA Southeast — AL + GA + SC medical facility construction.", naicsFocus: "236220", setAsideFocus: "SDVOSB" },
  { name: "VA Mid South Healthcare Network (VISN 9)", url: "https://www.va.gov/mid-south-healthcare/", category: "VA medical", agencyKind: "FEDERAL", agencyTier: "VA", agencyName: "VA VISN 9", geoScope: "REGIONAL", description: "VA Mid South — KY + TN + parts of MS / WV medical facility construction.", naicsFocus: "236220", setAsideFocus: "SDVOSB" },
  { name: "VA Southeast Louisiana (VISN 16)", url: "https://www.va.gov/south-central-healthcare/", category: "VA medical", agencyKind: "FEDERAL", agencyTier: "VA", agencyName: "VA VISN 16", geoScope: "REGIONAL", description: "VA South Central — LA + MS + AR + parts of TX / OK medical facility construction.", naicsFocus: "236220", setAsideFocus: "SDVOSB" },

  // ════════════════════════════════════════════════════════════════════
  // FEDERAL EXPANSION — civilian construction agencies
  // ════════════════════════════════════════════════════════════════════
  { name: "EPA Region 4 Procurement (SE)", url: "https://www.epa.gov/aboutepa/about-epa-region-4-southeast", category: "Federal regulatory", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "U.S. EPA Region 4", geoScope: "REGIONAL", description: "EPA Region 4 — covers AL, FL, GA, KY, MS, NC, SC, TN. Superfund site remediation + facility ops.", naicsFocus: "562910, 562211, 237990" },
  { name: "USDA Rural Development", url: "https://www.rd.usda.gov/about-rd/agencies", category: "Federal infrastructure", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "USDA Rural Development", geoScope: "FEDERAL", description: "USDA RD — community facilities, water/wastewater grants and loans for rural construction.", naicsFocus: "237110, 236220, 236210" },
  { name: "USDA Forest Service Southeast", url: "https://www.fs.usda.gov/main/r8/about-region", category: "Federal facility", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "USDA Forest Service Region 8", geoScope: "REGIONAL", description: "Forest Service Southern Region — recreation facility + road construction across 13 SE states.", naicsFocus: "237310, 236220" },
  { name: "National Park Service Southeast Region", url: "https://www.nps.gov/aboutus/southeast-region.htm", category: "Federal facility", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "NPS Southeast Region", geoScope: "REGIONAL", description: "NPS SE — visitor centers, lodges, trails, infrastructure across SE national parks.", naicsFocus: "236220, 237310" },
  { name: "FAA Southern Region Construction", url: "https://www.faa.gov/about/office_org/headquarters_offices/aso", category: "Federal aviation", agencyKind: "FEDERAL", agencyTier: "TRANSPORTATION", agencyName: "FAA Southern Region", geoScope: "REGIONAL", description: "FAA Southern Region — airport tower / radar / hangar construction.", naicsFocus: "237310, 237990" },
  { name: "FRA Federal Railroad Administration", url: "https://railroads.dot.gov/grants-loans-financial-assistance", category: "Federal rail", agencyKind: "FEDERAL", agencyTier: "TRANSPORTATION", agencyName: "Federal Railroad Administration", geoScope: "FEDERAL", description: "FRA grant programs — passenger rail + freight infrastructure.", naicsFocus: "237310" },
  { name: "FTA Federal Transit Administration", url: "https://www.transit.dot.gov/funding", category: "Federal transit", agencyKind: "FEDERAL", agencyTier: "TRANSPORTATION", agencyName: "Federal Transit Administration", geoScope: "FEDERAL", description: "FTA Capital Investment Grants for major transit construction.", naicsFocus: "237310, 237990" },
  { name: "FHWA Federal Highway Administration", url: "https://www.fhwa.dot.gov/business", category: "Federal highway", agencyKind: "FEDERAL", agencyTier: "TRANSPORTATION", agencyName: "Federal Highway Administration", geoScope: "FEDERAL", description: "FHWA — federal-aid highway construction (mostly state pass-through, but direct federal lands programs too).", naicsFocus: "237310" },
  { name: "Federal Lands Highway Eastern", url: "https://highways.dot.gov/federal-lands/efl", category: "Federal highway", agencyKind: "FEDERAL", agencyTier: "TRANSPORTATION", agencyName: "FHWA Eastern Federal Lands", geoScope: "REGIONAL", description: "Federal Lands Highway Eastern Division — Park, BIA, Forest Service road projects east of the Mississippi.", naicsFocus: "237310" },
  { name: "Coast Guard Procurement (SE)", url: "https://www.dcms.uscg.mil/Our-Organization/Assistant-Commandant-for-Acquisitions-CG-9/", category: "Federal homeland", agencyKind: "FEDERAL", agencyTier: "HOMELAND", agencyName: "U.S. Coast Guard", geoScope: "FEDERAL", description: "USCG facility / station construction. Heavy SE presence (FL, NC, VA, LA, MS).", naicsFocus: "236220" },
  { name: "TSA Procurement", url: "https://www.tsa.gov/about/business-opportunities", category: "Federal homeland", agencyKind: "FEDERAL", agencyTier: "HOMELAND", agencyName: "Transportation Security Administration", geoScope: "FEDERAL", description: "TSA — airport checkpoint construction + facility upgrades.", naicsFocus: "236220" },
  { name: "ICE / CBP Facility Procurement", url: "https://www.cbp.gov/about/contracting", category: "Federal homeland", agencyKind: "FEDERAL", agencyTier: "HOMELAND", agencyName: "CBP / ICE", geoScope: "FEDERAL", description: "CBP / ICE detention + processing facility construction.", naicsFocus: "236220" },
  { name: "GSA Public Buildings Service", url: "https://www.gsa.gov/about-us/organization/public-buildings-service", category: "Federal facility", agencyKind: "FEDERAL", agencyTier: "GSA", agencyName: "GSA PBS", geoScope: "FEDERAL", description: "GSA PBS — federal courthouse, office building, land port-of-entry construction.", naicsFocus: "236220" },
  { name: "GSA PBS Region 4 (Atlanta)", url: "https://www.gsa.gov/about-us/regions/welcome-to-the-southeast-sunbelt-region-4", category: "Federal facility", agencyKind: "FEDERAL", agencyTier: "GSA", agencyName: "GSA Region 4", geoScope: "REGIONAL", description: "GSA Southeast Sunbelt Region — federal facility construction across 8 SE states.", naicsFocus: "236220" },
  { name: "Smithsonian Procurement", url: "https://www.si.edu/ofeo/procurement", category: "Federal cultural", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "Smithsonian Institution", geoScope: "FEDERAL", description: "Smithsonian museum + research facility construction.", naicsFocus: "236220" },
  { name: "Library of Congress Procurement", url: "https://www.loc.gov/contracts/", category: "Federal cultural", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "Library of Congress", geoScope: "FEDERAL", description: "Library of Congress facility + storage construction.", naicsFocus: "236220" },
  { name: "NIH Office of Research Facilities", url: "https://orf.od.nih.gov/", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "NIH ORF", geoScope: "FEDERAL", description: "NIH research facility construction (Bethesda + RTP NC).", naicsFocus: "236220, 541330" },
  { name: "NSF Major Facilities Construction", url: "https://www.nsf.gov/bfa/lfo/", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "National Science Foundation", geoScope: "FEDERAL", description: "NSF major research equipment + facilities construction (telescopes, polar facilities, ocean labs).", naicsFocus: "236220, 541330" },
  { name: "NOAA Procurement", url: "https://www.commerce.gov/oam/policy/procurement", category: "Federal facility", agencyKind: "FEDERAL", agencyTier: "CIVILIAN", agencyName: "NOAA / Department of Commerce", geoScope: "FEDERAL", description: "NOAA — weather facility + research lab + ocean monitoring station construction.", naicsFocus: "236220" },
  { name: "DOE Oak Ridge National Lab", url: "https://www.ornl.gov/contact/business-with-ornl", category: "Federal R&D facility", agencyKind: "FEDERAL", agencyTier: "ENERGY", agencyName: "Oak Ridge National Laboratory", geoScope: "REGIONAL", geoState: "TN", description: "ORNL — national lab construction + facility ops in Oak Ridge, TN.", naicsFocus: "236220, 541330" },
  { name: "DOE Savannah River Site", url: "https://www.energy.gov/em/savannah-river-site", category: "Federal cleanup", agencyKind: "FEDERAL", agencyTier: "ENERGY", agencyName: "DOE Savannah River Site", geoScope: "REGIONAL", geoState: "SC", description: "Savannah River Site — DOE EM cleanup + facility construction near Aiken, SC.", naicsFocus: "562910, 236220" },
  { name: "DOE Y-12 National Security Complex", url: "https://www.y12.doe.gov/about/contracting-and-procurement", category: "Federal facility", agencyKind: "FEDERAL", agencyTier: "ENERGY", agencyName: "Y-12 NSC", geoScope: "REGIONAL", geoState: "TN", description: "Y-12 — DOE/NNSA nuclear security complex construction in Oak Ridge, TN.", naicsFocus: "236220" },
  { name: "Federal Reserve Bank of Atlanta Procurement", url: "https://www.atlantafed.org/about/procurement.aspx", category: "Federal banking", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "Federal Reserve Bank of Atlanta", geoScope: "REGIONAL", description: "FRB Atlanta — banking facility construction + branch / cash-processing operations.", naicsFocus: "236220" },
  { name: "Federal Reserve Bank of Richmond Procurement", url: "https://www.richmondfed.org/about_us/contracting", category: "Federal banking", agencyKind: "FEDERAL", agencyTier: "INDEPENDENT", agencyName: "Federal Reserve Bank of Richmond", geoScope: "REGIONAL", description: "FRB Richmond — Fifth District banking facility construction (DC, MD, VA, WV, NC, SC).", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — ALABAMA
  // ════════════════════════════════════════════════════════════════════
  { name: "Alabama Procurement (DOF)", url: "https://purchasing.alabama.gov/business/", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of Alabama", geoScope: "STATE", geoState: "AL", description: "Alabama Department of Finance state purchasing.", naicsFocus: "236220" },
  { name: "ALDOT Bid Letting", url: "https://www.dot.state.al.us/conweb/", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "Alabama DOT", geoScope: "STATE", geoState: "AL", description: "Alabama DOT bid lettings for road, bridge, and infrastructure.", naicsFocus: "237310" },
  { name: "City of Birmingham Procurement", url: "https://www.birminghamal.gov/finance/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Birmingham, AL", geoScope: "CITY", geoCity: "Birmingham", geoState: "AL", description: "Birmingham municipal procurement.", naicsFocus: "236220" },
  { name: "City of Montgomery Procurement", url: "https://www.montgomeryal.gov/business/procurement-purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Montgomery, AL", geoScope: "CITY", geoCity: "Montgomery", geoState: "AL", description: "Montgomery state-capital procurement.", naicsFocus: "236220" },
  { name: "City of Mobile Procurement", url: "https://www.cityofmobile.org/departments/finance/purchasing/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Mobile, AL", geoScope: "CITY", geoCity: "Mobile", geoState: "AL", description: "Mobile gulf-coast city procurement; significant port facility work.", naicsFocus: "236220, 237990" },
  { name: "City of Huntsville Procurement", url: "https://www.huntsvilleal.gov/business/bid-opportunities/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Huntsville, AL", geoScope: "CITY", geoCity: "Huntsville", geoState: "AL", description: "Huntsville — fast-growth city with NASA + DoD spillover work.", naicsFocus: "236220" },
  { name: "City of Tuscaloosa Procurement", url: "https://www.tuscaloosa.com/government/finance-department/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Tuscaloosa, AL", geoScope: "CITY", geoCity: "Tuscaloosa", geoState: "AL", description: "Tuscaloosa procurement.", naicsFocus: "236220" },
  { name: "Jefferson County Purchasing", url: "https://www.jccal.org/Default.asp?ID=276", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Jefferson County, AL", geoScope: "COUNTY", geoState: "AL", description: "Jefferson County, AL — Birmingham metro.", naicsFocus: "236220" },
  { name: "Madison County Procurement", url: "https://www.madisoncountyal.gov/government/departments/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Madison County, AL", geoScope: "COUNTY", geoState: "AL", description: "Madison County — Huntsville metro.", naicsFocus: "236220" },
  { name: "Mobile County Procurement", url: "https://www.mobilecountyal.gov/government/gov_purchasing.html", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Mobile County, AL", geoScope: "COUNTY", geoState: "AL", description: "Mobile County procurement.", naicsFocus: "236220" },
  { name: "Montgomery County Procurement", url: "https://www.mc-ala.org/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Montgomery County, AL", geoScope: "COUNTY", geoState: "AL", description: "Montgomery County procurement.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — ARKANSAS
  // ════════════════════════════════════════════════════════════════════
  { name: "Arkansas Office of State Procurement", url: "https://www.arkansas.gov/dfa/procurement/", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of Arkansas", geoScope: "STATE", geoState: "AR", description: "Arkansas Department of Finance + Administration state procurement.", naicsFocus: "236220" },
  { name: "ARDOT Bid Letting", url: "https://www.ardot.gov/divisions/program-management/contracts-section/", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "Arkansas DOT", geoScope: "STATE", geoState: "AR", description: "Arkansas DOT contracts section.", naicsFocus: "237310" },
  { name: "City of Little Rock Procurement", url: "https://www.littlerock.gov/city-administration/finance/procurement-services/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Little Rock, AR", geoScope: "CITY", geoCity: "Little Rock", geoState: "AR", description: "Little Rock state capital procurement.", naicsFocus: "236220" },
  { name: "City of Fayetteville Procurement", url: "https://www.fayetteville-ar.gov/3232/Purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Fayetteville, AR", geoScope: "CITY", geoCity: "Fayetteville", geoState: "AR", description: "Fayetteville procurement; University of AR spillover.", naicsFocus: "236220" },
  { name: "Pulaski County Purchasing", url: "https://www.pulaskicounty.net/county/government/departments/finance-and-administration/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Pulaski County, AR", geoScope: "COUNTY", geoState: "AR", description: "Pulaski County, AR — Little Rock metro.", naicsFocus: "236220" },
  { name: "Benton County Procurement", url: "https://www.bentoncountyar.gov/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Benton County, AR", geoScope: "COUNTY", geoState: "AR", description: "Benton County — NW Arkansas (Bentonville/Fayetteville metro).", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — FLORIDA (heavy expansion — large state, lots of construction)
  // ════════════════════════════════════════════════════════════════════
  // FDOT main contracts page is already in PORTAL_CATALOG (FDOT
  // Bidding & Contracting); we don't duplicate it here. The
  // consultant/professional-services lane has its own URL below.
  { name: "Florida Department of Management Services", url: "https://www.dms.myflorida.com/business_operations/state_purchasing", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of Florida DMS", geoScope: "STATE", geoState: "FL", description: "Florida DMS — state contracts beyond MyFloridaMP.", naicsFocus: "236220" },
  { name: "Florida Turnpike Enterprise Construction", url: "https://floridasturnpike.com/business/contractor-information/", category: "Authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "Florida's Turnpike Enterprise", geoScope: "STATE", geoState: "FL", description: "Florida Turnpike — major statewide tolled-roadway construction program.", naicsFocus: "237310" },
  { name: "JaxPort (Jacksonville Port Authority)", url: "https://www.jaxport.com/about/business-jaxport/procurement/", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "JaxPort", geoScope: "REGIONAL", geoState: "FL", description: "Jacksonville port authority — terminal + dredging construction.", naicsFocus: "237990, 237310" },
  { name: "Port Tampa Bay Procurement", url: "https://www.porttb.com/page/procurement", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "Port Tampa Bay", geoScope: "REGIONAL", geoState: "FL", description: "Tampa Bay port authority procurement.", naicsFocus: "237990" },
  { name: "Port of Miami Procurement", url: "https://www.miamidade.gov/portmiami/business-services.asp", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "PortMiami", geoScope: "REGIONAL", geoState: "FL", description: "PortMiami capital improvements via Miami-Dade.", naicsFocus: "237990" },
  { name: "City of Jacksonville Procurement", url: "https://www.jacksonville.gov/departments/finance/procurement.aspx", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Jacksonville, FL", geoScope: "CITY", geoCity: "Jacksonville", geoState: "FL", description: "Jacksonville — largest city by area in continental US.", naicsFocus: "236220" },
  { name: "City of Miami Procurement", url: "https://www.miamigov.com/Government/Departments-Organizations/Procurement", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Miami, FL", geoScope: "CITY", geoCity: "Miami", geoState: "FL", description: "City of Miami procurement (separate from Miami-Dade County).", naicsFocus: "236220" },
  { name: "City of Tampa Procurement", url: "https://www.tampa.gov/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Tampa, FL", geoScope: "CITY", geoCity: "Tampa", geoState: "FL", description: "Tampa city procurement.", naicsFocus: "236220" },
  { name: "City of Orlando Procurement", url: "https://www.orlando.gov/Our-Government/Departments-Offices/Business-and-Financial-Services/Purchasing-Services", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Orlando, FL", geoScope: "CITY", geoCity: "Orlando", geoState: "FL", description: "Orlando city procurement.", naicsFocus: "236220" },
  { name: "City of St. Petersburg Procurement", url: "https://www.stpete.org/business/purchasing/index.php", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of St. Petersburg, FL", geoScope: "CITY", geoCity: "St. Petersburg", geoState: "FL", description: "St. Petersburg city procurement.", naicsFocus: "236220" },
  { name: "City of Fort Lauderdale Procurement", url: "https://www.fortlauderdale.gov/government/departments-i-z/procurement-services-division", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Fort Lauderdale, FL", geoScope: "CITY", geoCity: "Fort Lauderdale", geoState: "FL", description: "Fort Lauderdale city procurement.", naicsFocus: "236220" },
  { name: "City of Tallahassee Procurement", url: "https://www.talgov.com/purchasing/purchasing.aspx", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Tallahassee, FL", geoScope: "CITY", geoCity: "Tallahassee", geoState: "FL", description: "Tallahassee state-capital procurement.", naicsFocus: "236220" },
  { name: "Hillsborough County Procurement", url: "https://www.hillsboroughcounty.org/en/businesses/working-with-the-county", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Hillsborough County, FL", geoScope: "COUNTY", geoState: "FL", description: "Hillsborough County, FL — Tampa metro.", naicsFocus: "236220" },
  { name: "Orange County Procurement", url: "https://www.ocfl.net/Business/DoingBusinessWithOrangeCountyGovernment.aspx", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Orange County, FL", geoScope: "COUNTY", geoState: "FL", description: "Orange County, FL — Orlando metro.", naicsFocus: "236220" },
  { name: "Broward County Purchasing", url: "https://www.broward.org/Purchasing/Pages/Default.aspx", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Broward County, FL", geoScope: "COUNTY", geoState: "FL", description: "Broward County, FL — Fort Lauderdale metro.", naicsFocus: "236220" },
  { name: "Palm Beach County Procurement", url: "https://discover.pbcgov.org/PALMBEACHCOUNTYFL/PUR/Pages/default.aspx", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Palm Beach County, FL", geoScope: "COUNTY", geoState: "FL", description: "Palm Beach County, FL.", naicsFocus: "236220" },
  { name: "Duval County Procurement", url: "https://www.duvalschools.org/page/2169", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Duval County, FL", geoScope: "COUNTY", geoState: "FL", description: "Duval County (Jacksonville) — combined city/county under Consolidated Government.", naicsFocus: "236220" },
  { name: "Pinellas County Purchasing", url: "https://www.pinellascounty.org/purchase/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Pinellas County, FL", geoScope: "COUNTY", geoState: "FL", description: "Pinellas County, FL — St. Petersburg/Clearwater.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — GEORGIA
  // ════════════════════════════════════════════════════════════════════
  { name: "Georgia Ports Authority Procurement", url: "https://gaports.com/business/", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "Georgia Ports Authority", geoScope: "REGIONAL", geoState: "GA", description: "GPA — Port of Savannah + Brunswick. Major terminal expansion programs.", naicsFocus: "237990" },
  { name: "Georgia State Road and Tollway Authority", url: "https://www.srta.ga.gov/", category: "Authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "GA SRTA", geoScope: "STATE", geoState: "GA", description: "Georgia state tollway authority.", naicsFocus: "237310" },
  { name: "MARTA Procurement", url: "https://www.itsmarta.com/Procurement.aspx", category: "Transit authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "MARTA", geoScope: "REGIONAL", geoState: "GA", description: "Atlanta Metropolitan Atlanta Rapid Transit Authority — rail + bus capital programs.", naicsFocus: "237310, 237990" },
  { name: "City of Augusta Procurement", url: "https://www.augustaga.gov/183/Procurement", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Augusta, GA", geoScope: "CITY", geoCity: "Augusta", geoState: "GA", description: "Augusta-Richmond County consolidated procurement.", naicsFocus: "236220" },
  { name: "City of Savannah Procurement", url: "https://www.savannahga.gov/137/Purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Savannah, GA", geoScope: "CITY", geoCity: "Savannah", geoState: "GA", description: "Savannah city procurement; significant port-adjacent work.", naicsFocus: "236220" },
  { name: "City of Columbus Procurement", url: "https://www.columbusga.gov/finance/purchasing.htm", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Columbus, GA", geoScope: "CITY", geoCity: "Columbus", geoState: "GA", description: "Columbus-Muscogee consolidated procurement.", naicsFocus: "236220" },
  { name: "City of Macon Procurement", url: "https://www.maconbibb.us/purchasing/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "Macon-Bibb County, GA", geoScope: "CITY", geoCity: "Macon", geoState: "GA", description: "Macon-Bibb consolidated procurement.", naicsFocus: "236220" },
  { name: "Fulton County Purchasing", url: "https://www.fultoncountyga.gov/inside-fulton-county/fulton-county-departments/purchasing-and-contract-compliance", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Fulton County, GA", geoScope: "COUNTY", geoState: "GA", description: "Fulton County, GA — Atlanta metro core.", naicsFocus: "236220" },
  { name: "Gwinnett County Purchasing", url: "https://www.gwinnettcounty.com/web/gwinnett/departments/financialservices/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Gwinnett County, GA", geoScope: "COUNTY", geoState: "GA", description: "Gwinnett County, GA — Atlanta NE metro.", naicsFocus: "236220" },
  { name: "Cobb County Purchasing", url: "https://www.cobbcounty.org/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Cobb County, GA", geoScope: "COUNTY", geoState: "GA", description: "Cobb County, GA — Atlanta NW metro.", naicsFocus: "236220" },
  { name: "DeKalb County Purchasing", url: "https://www.dekalbcountyga.gov/purchasing-contracting", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "DeKalb County, GA", geoScope: "COUNTY", geoState: "GA", description: "DeKalb County, GA — Atlanta E metro.", naicsFocus: "236220" },
  { name: "Chatham County Purchasing", url: "https://www.chathamcountyga.gov/government/departments/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Chatham County, GA", geoScope: "COUNTY", geoState: "GA", description: "Chatham County, GA — Savannah metro.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — KENTUCKY
  // ════════════════════════════════════════════════════════════════════
  { name: "Kentucky Finance and Administration Cabinet", url: "https://finance.ky.gov/services/eprocurement/Pages/default.aspx", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "Commonwealth of Kentucky", geoScope: "STATE", geoState: "KY", description: "Kentucky eProcurement portal.", naicsFocus: "236220" },
  { name: "KYTC Bid Letting", url: "https://transportation.ky.gov/Construction-Procurement/Pages/default.aspx", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "Kentucky Transportation Cabinet", geoScope: "STATE", geoState: "KY", description: "KYTC construction procurement. Verified scraping via generic-html (extracts proposal PDFs by county code).", naicsFocus: "237310", scraperKind: "HTML", scraperModule: "generic-html" },
  { name: "City of Louisville Procurement", url: "https://louisvilleky.gov/government/office-management-budget/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "Louisville Metro Government, KY", geoScope: "CITY", geoCity: "Louisville", geoState: "KY", description: "Louisville Metro consolidated procurement.", naicsFocus: "236220" },
  { name: "City of Lexington Purchasing", url: "https://www.lexingtonky.gov/departments/government-operations-services/division-central-purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "Lexington-Fayette Urban County, KY", geoScope: "CITY", geoCity: "Lexington", geoState: "KY", description: "Lexington-Fayette consolidated procurement.", naicsFocus: "236220" },
  { name: "Jefferson County (KY) Public Schools Procurement", url: "https://www.jefferson.kyschools.us/departments/finance/purchasing-supply", category: "School district", agencyKind: "AUTHORITY", agencyTier: "EDUCATION", agencyName: "JCPS Louisville, KY", geoScope: "COUNTY", geoState: "KY", description: "Largest school district in KY — facility renovation programs.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — LOUISIANA
  // ════════════════════════════════════════════════════════════════════
  { name: "Louisiana LaPAC", url: "https://wwwcfprd.doa.louisiana.gov/osp/lapac/dspBid.cfm", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of Louisiana", geoScope: "STATE", geoState: "LA", description: "LaPAC — Louisiana state procurement bid notices.", naicsFocus: "236220" },
  { name: "DOTD Bid Letting", url: "https://wwwsp.dotd.la.gov/Inside_LaDOTD/Divisions/Engineering/Construction/Pages/default.aspx", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "Louisiana DOTD", geoScope: "STATE", geoState: "LA", description: "Louisiana DOTD construction lettings.", naicsFocus: "237310" },
  { name: "City of New Orleans Procurement", url: "https://www.nola.gov/finance/bureau-of-purchasing/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of New Orleans, LA", geoScope: "CITY", geoCity: "New Orleans", geoState: "LA", description: "New Orleans procurement; ongoing post-Katrina + climate-resilience programs.", naicsFocus: "236220, 237990" },
  { name: "City of Baton Rouge Procurement", url: "https://www.brla.gov/government/departments-divisions/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Baton Rouge / East Baton Rouge Parish", geoScope: "CITY", geoCity: "Baton Rouge", geoState: "LA", description: "Baton Rouge / East Baton Rouge Parish consolidated procurement.", naicsFocus: "236220" },
  { name: "Port of New Orleans Procurement", url: "https://portnola.com/about/business-with-port-of-new-orleans", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "Port of New Orleans", geoScope: "REGIONAL", geoState: "LA", description: "Port NOLA — terminal + warehouse construction.", naicsFocus: "237990" },
  { name: "Orleans Parish School Board", url: "https://www.opsb.us/business-services/", category: "School district", agencyKind: "AUTHORITY", agencyTier: "EDUCATION", agencyName: "Orleans Parish School Board", geoScope: "COUNTY", geoState: "LA", description: "Orleans Parish school construction.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — MISSISSIPPI
  // ════════════════════════════════════════════════════════════════════
  { name: "Mississippi Department of Finance and Administration", url: "https://www.dfa.ms.gov/dfa-offices/purchasing-travel-and-fleet/", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of Mississippi", geoScope: "STATE", geoState: "MS", description: "MS DFA state procurement.", naicsFocus: "236220" },
  { name: "MDOT Bid Letting", url: "https://mdot.ms.gov/portal/contracts.aspx", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "Mississippi DOT", geoScope: "STATE", geoState: "MS", description: "Mississippi DOT contracts.", naicsFocus: "237310" },
  { name: "City of Jackson Procurement", url: "https://www.jacksonms.gov/government/department/finance-administration/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Jackson, MS", geoScope: "CITY", geoCity: "Jackson", geoState: "MS", description: "Jackson state-capital procurement.", naicsFocus: "236220" },
  { name: "City of Gulfport Procurement", url: "https://www.gulfport-ms.gov/business/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Gulfport, MS", geoScope: "CITY", geoCity: "Gulfport", geoState: "MS", description: "Gulfport gulf-coast procurement.", naicsFocus: "236220" },
  { name: "Hinds County Procurement", url: "https://www.hindscountyms.com/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Hinds County, MS", geoScope: "COUNTY", geoState: "MS", description: "Hinds County, MS — Jackson metro.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — NORTH CAROLINA
  // ════════════════════════════════════════════════════════════════════
  { name: "NC eProcurement", url: "https://eprocurement.nc.gov/", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of North Carolina", geoScope: "STATE", geoState: "NC", description: "NC eProcurement central portal (replaces older IPS for new solicitations).", naicsFocus: "236220" },
  { name: "NCDOT Letting Schedule", url: "https://connect.ncdot.gov/letting/Pages/default.aspx", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "North Carolina DOT", geoScope: "STATE", geoState: "NC", description: "NCDOT letting schedule + bid documents.", naicsFocus: "237310" },
  { name: "NC Turnpike Authority Procurement", url: "https://www.ncdot.gov/divisions/turnpike/Pages/default.aspx", category: "Authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "NC Turnpike Authority", geoScope: "STATE", geoState: "NC", description: "NCTA — toll roads (Triangle Expressway, Monroe Expressway).", naicsFocus: "237310" },
  { name: "City of Charlotte Procurement", url: "https://www.charlottenc.gov/Growth-and-Development/Doing-Business-with-the-City", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Charlotte, NC", geoScope: "CITY", geoCity: "Charlotte", geoState: "NC", description: "Charlotte city procurement.", naicsFocus: "236220" },
  { name: "City of Raleigh Procurement", url: "https://raleighnc.gov/business/services/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Raleigh, NC", geoScope: "CITY", geoCity: "Raleigh", geoState: "NC", description: "Raleigh city procurement.", naicsFocus: "236220" },
  { name: "City of Greensboro Procurement", url: "https://www.greensboro-nc.gov/departments/financial-administrative-services/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Greensboro, NC", geoScope: "CITY", geoCity: "Greensboro", geoState: "NC", description: "Greensboro city procurement.", naicsFocus: "236220" },
  { name: "City of Durham Procurement", url: "https://www.durhamnc.gov/210/Procurement", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Durham, NC", geoScope: "CITY", geoCity: "Durham", geoState: "NC", description: "Durham city procurement.", naicsFocus: "236220" },
  { name: "City of Winston-Salem Procurement", url: "https://www.cityofws.org/2046/Purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Winston-Salem, NC", geoScope: "CITY", geoCity: "Winston-Salem", geoState: "NC", description: "Winston-Salem city procurement.", naicsFocus: "236220" },
  { name: "Mecklenburg County Procurement", url: "https://www.mecknc.gov/CountyManagersOffice/Procurement/Pages/default.aspx", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Mecklenburg County, NC", geoScope: "COUNTY", geoState: "NC", description: "Mecklenburg County, NC — Charlotte metro.", naicsFocus: "236220" },
  { name: "Wake County Procurement", url: "https://www.wake.gov/departments-government/finance/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Wake County, NC", geoScope: "COUNTY", geoState: "NC", description: "Wake County, NC — Raleigh metro.", naicsFocus: "236220" },
  { name: "Guilford County Procurement", url: "https://www.guilfordcountync.gov/our-county/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Guilford County, NC", geoScope: "COUNTY", geoState: "NC", description: "Guilford County, NC — Greensboro metro.", naicsFocus: "236220" },
  { name: "Forsyth County Purchasing", url: "https://www.forsyth.cc/Finance/Purchasing/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Forsyth County, NC", geoScope: "COUNTY", geoState: "NC", description: "Forsyth County, NC — Winston-Salem metro.", naicsFocus: "236220" },
  { name: "Durham County Procurement", url: "https://www.dconc.gov/county-departments/departments-a-e/budget-and-management-services/county-procurement", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Durham County, NC", geoScope: "COUNTY", geoState: "NC", description: "Durham County procurement.", naicsFocus: "236220" },
  { name: "Cumberland County Purchasing", url: "https://www.cumberlandcountync.gov/departments/finance/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Cumberland County, NC", geoScope: "COUNTY", geoState: "NC", description: "Cumberland County (Fayetteville/Fort Liberty) procurement.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — SOUTH CAROLINA (already had Charleston city/county)
  // ════════════════════════════════════════════════════════════════════
  { name: "SCEIS State Solicitations", url: "https://procurement.sc.gov/vendor", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of South Carolina", geoScope: "STATE", geoState: "SC", description: "SC state procurement vendor portal.", naicsFocus: "236220" },
  { name: "City of Columbia Procurement", url: "https://www.columbiasc.gov/depts/finance/business/purchasing/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Columbia, SC", geoScope: "CITY", geoCity: "Columbia", geoState: "SC", description: "Columbia state-capital procurement.", naicsFocus: "236220" },
  { name: "City of Greenville Procurement", url: "https://www.greenvillesc.gov/270/Purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Greenville, SC", geoScope: "CITY", geoCity: "Greenville", geoState: "SC", description: "Greenville city procurement; major upstate growth market.", naicsFocus: "236220" },
  { name: "City of North Charleston Procurement", url: "https://www.northcharleston.org/business/purchasing/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of North Charleston, SC", geoScope: "CITY", geoCity: "North Charleston", geoState: "SC", description: "North Charleston procurement.", naicsFocus: "236220" },
  { name: "Town of Mount Pleasant Procurement", url: "https://www.mountpleasantsc.com/business/business-with-the-town/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "Town of Mount Pleasant, SC", geoScope: "CITY", geoCity: "Mount Pleasant", geoState: "SC", description: "Mount Pleasant town procurement.", naicsFocus: "236220" },
  { name: "Greenville County Procurement", url: "https://www.greenvillecounty.org/Procurement/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Greenville County, SC", geoScope: "COUNTY", geoState: "SC", description: "Greenville County procurement.", naicsFocus: "236220" },
  { name: "Richland County Procurement", url: "https://www.richlandcountysc.gov/Government/Departments/Administrative-Services/Procurement", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Richland County, SC", geoScope: "COUNTY", geoState: "SC", description: "Richland County, SC — Columbia metro.", naicsFocus: "236220" },
  { name: "Berkeley County Procurement", url: "https://berkeleycountysc.gov/dept/procurement/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Berkeley County, SC", geoScope: "COUNTY", geoState: "SC", description: "Berkeley County, SC — north of Charleston.", naicsFocus: "236220" },
  { name: "Horry County Procurement", url: "https://www.horrycountysc.gov/departments/procurement/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Horry County, SC", geoScope: "COUNTY", geoState: "SC", description: "Horry County, SC — Myrtle Beach metro.", naicsFocus: "236220" },
  { name: "Spartanburg County Procurement", url: "https://www.spartanburgcounty.org/213/Procurement", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Spartanburg County, SC", geoScope: "COUNTY", geoState: "SC", description: "Spartanburg County procurement.", naicsFocus: "236220" },
  { name: "South Carolina Ports Authority", url: "https://scspa.com/about/business-opportunities/", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "South Carolina Ports Authority", geoScope: "STATE", geoState: "SC", description: "SC Ports — Charleston, Georgetown, inland ports. Terminal expansion programs.", naicsFocus: "237990" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — TENNESSEE
  // ════════════════════════════════════════════════════════════════════
  { name: "TN State Procurement Edison", url: "https://www.tn.gov/generalservices/procurement.html", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of Tennessee", geoScope: "STATE", geoState: "TN", description: "TN state procurement (Edison eProcurement system).", naicsFocus: "236220" },
  { name: "TDOT Construction Contracts", url: "https://www.tn.gov/tdot/construction-division.html", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "Tennessee DOT", geoScope: "STATE", geoState: "TN", description: "TDOT construction contracts.", naicsFocus: "237310" },
  { name: "Metro Nashville Procurement", url: "https://www.nashville.gov/departments/finance/procurement", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "Metro Nashville/Davidson County, TN", geoScope: "CITY", geoCity: "Nashville", geoState: "TN", description: "Metro Nashville/Davidson consolidated procurement.", naicsFocus: "236220" },
  { name: "City of Memphis Procurement", url: "https://www.memphistn.gov/business/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Memphis, TN", geoScope: "CITY", geoCity: "Memphis", geoState: "TN", description: "Memphis city procurement.", naicsFocus: "236220" },
  { name: "City of Knoxville Procurement", url: "https://www.knoxvilletn.gov/government/city_departments_offices/finance/purchasing/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Knoxville, TN", geoScope: "CITY", geoCity: "Knoxville", geoState: "TN", description: "Knoxville city procurement.", naicsFocus: "236220" },
  { name: "City of Chattanooga Procurement", url: "https://www.chattanooga.gov/finance-and-administration/purchasing", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Chattanooga, TN", geoScope: "CITY", geoCity: "Chattanooga", geoState: "TN", description: "Chattanooga city procurement.", naicsFocus: "236220" },
  { name: "Shelby County Procurement", url: "https://www.shelbycountytn.gov/175/Purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Shelby County, TN", geoScope: "COUNTY", geoState: "TN", description: "Shelby County, TN — Memphis metro.", naicsFocus: "236220" },
  { name: "Knox County Purchasing", url: "https://knoxcounty.org/purchasing/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Knox County, TN", geoScope: "COUNTY", geoState: "TN", description: "Knox County, TN — Knoxville metro.", naicsFocus: "236220" },
  { name: "Hamilton County Purchasing (TN)", url: "https://www.hamiltontn.gov/Purchasing/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Hamilton County, TN", geoScope: "COUNTY", geoState: "TN", description: "Hamilton County, TN — Chattanooga metro.", naicsFocus: "236220" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — VIRGINIA (already had eVA, VDOT)
  // ════════════════════════════════════════════════════════════════════
  { name: "Hampton Roads Transit Procurement", url: "https://gohrt.com/about/business-opportunities/", category: "Transit authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "Hampton Roads Transit", geoScope: "REGIONAL", geoState: "VA", description: "HRT — bus + light rail capital programs.", naicsFocus: "237310" },
  { name: "City of Richmond Procurement", url: "https://www.rva.gov/procurement-services", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Richmond, VA", geoScope: "CITY", geoCity: "Richmond", geoState: "VA", description: "Richmond state-capital procurement.", naicsFocus: "236220" },
  { name: "City of Virginia Beach Procurement", url: "https://www.vbgov.com/government/departments/finance/purchasing/Pages/default.aspx", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Virginia Beach, VA", geoScope: "CITY", geoCity: "Virginia Beach", geoState: "VA", description: "Virginia Beach city procurement.", naicsFocus: "236220" },
  { name: "City of Norfolk Procurement", url: "https://www.norfolk.gov/3017/Procurement", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Norfolk, VA", geoScope: "CITY", geoCity: "Norfolk", geoState: "VA", description: "Norfolk city procurement.", naicsFocus: "236220" },
  { name: "City of Chesapeake Procurement", url: "https://www.cityofchesapeake.net/Government/City-Departments/Departments/Finance-Department/Purchasing.htm", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Chesapeake, VA", geoScope: "CITY", geoCity: "Chesapeake", geoState: "VA", description: "Chesapeake city procurement.", naicsFocus: "236220" },
  { name: "Fairfax County Purchasing", url: "https://www.fairfaxcounty.gov/finance/dpsm/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Fairfax County, VA", geoScope: "COUNTY", geoState: "VA", description: "Fairfax County — DC metro; massive school + transit construction.", naicsFocus: "236220" },
  { name: "Prince William County Purchasing", url: "https://www.pwcva.gov/department/finance/purchasing", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Prince William County, VA", geoScope: "COUNTY", geoState: "VA", description: "Prince William County, VA — DC south metro.", naicsFocus: "236220" },
  { name: "Loudoun County Procurement", url: "https://www.loudoun.gov/237/Procurement", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Loudoun County, VA", geoScope: "COUNTY", geoState: "VA", description: "Loudoun County — DC NW metro; massive data center construction market.", naicsFocus: "236220" },
  { name: "Henrico County Purchasing", url: "https://henrico.us/finance/purchasing/", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Henrico County, VA", geoScope: "COUNTY", geoState: "VA", description: "Henrico County, VA — Richmond metro.", naicsFocus: "236220" },
  { name: "Chesterfield County Procurement", url: "https://www.chesterfield.gov/189/Procurement", category: "County", agencyKind: "COUNTY", agencyTier: "CIVILIAN", agencyName: "Chesterfield County, VA", geoScope: "COUNTY", geoState: "VA", description: "Chesterfield County, VA — Richmond south metro.", naicsFocus: "236220" },
  { name: "Virginia Port Authority Procurement", url: "https://www.portofvirginia.com/business/", category: "Port authority", agencyKind: "AUTHORITY", agencyTier: "TRANSPORTATION", agencyName: "Virginia Port Authority", geoScope: "STATE", geoState: "VA", description: "VPA — Norfolk + Virginia International Terminals.", naicsFocus: "237990" },

  // ════════════════════════════════════════════════════════════════════
  // STATE — WEST VIRGINIA
  // ════════════════════════════════════════════════════════════════════
  { name: "WV Purchasing Division", url: "https://www.state.wv.us/admin/purchase/", category: "State procurement", agencyKind: "STATE", agencyTier: "CIVILIAN", agencyName: "State of West Virginia", geoScope: "STATE", geoState: "WV", description: "WV statewide purchasing.", naicsFocus: "236220" },
  { name: "WVDOH Bid Letting", url: "https://transportation.wv.gov/highways/contractadmin/Pages/default.aspx", category: "State DOT", agencyKind: "STATE", agencyTier: "TRANSPORTATION", agencyName: "West Virginia DOT", geoScope: "STATE", geoState: "WV", description: "WVDOH highway construction lettings.", naicsFocus: "237310" },
  { name: "City of Charleston (WV) Procurement", url: "https://www.cityofcharleston.org/government/departments/finance/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Charleston, WV", geoScope: "CITY", geoCity: "Charleston", geoState: "WV", description: "Charleston state-capital procurement.", naicsFocus: "236220" },
  { name: "City of Huntington (WV) Procurement", url: "https://www.cityofhuntington.com/business/", category: "Municipal", agencyKind: "MUNICIPAL", agencyTier: "CIVILIAN", agencyName: "City of Huntington, WV", geoScope: "CITY", geoCity: "Huntington", geoState: "WV", description: "Huntington city procurement.", naicsFocus: "236220" },
];
